### PR TITLE
Merge of PRESTUS feature updates

### PR DESCRIPTION
**Pull request by jkosciessa**
Hi all,

I have merged previous changes in the DI master branch (i.e., @KTZ228's changes) and @eleonoracarpino's [open pull request](https://github.com/Donders-Institute/PRESTUS/pull/31) into my recent version.

This includes small feature updates:
- calculation and plotting of CEM43 heating values (@sirmrmarty)
- required external tools (e.g., kWave) are included as submodules; this may have consequences for binary downloads (?)

I have also merged @eleonoracarpino's _pseudoCT_ branch. Despite rebasing that branch, this turned out messier than I hoped, so I had to manually redo some recent changes.

I am currently testing this full merge, and will also try out the pseudoCT implementation. If I run into hiccups, I will update this pull request.

It would be great if someone else can also validate this version prior to a merge.

### CODE REVIEW

**Comment by jkosciessa** [comment]
Commit [f14f5e0](https://github.com/Donders-Institute/PRESTUS/pull/34/commits/f14f5e07d815d3594c460c8796baa88cc59ce56f) integrated the three parts of the pseudoCT code into a continuous function with relative paths etc.

Successfully ran this with a Donders 2deg UTE image. All fixed parameters, so no dependencies (beyond software toolboxes). Added an example call script as part of the documentation.

**Comment by mekman** [comment]
@jkosciessa do you agree that I can add the .Rhistory to .gitignore bc we don't need it, right?

**Comment by jkosciessa** [comment]
Yes, but let's first delete it, otherwise it will remain in the repo forever. Taking care of it now.

**Comment by jkosciessa** [comment]
[3195d93](https://github.com/Donders-Institute/PRESTUS/pull/34/commits/3195d935f996314e78523bb504019b848fd826f1) is a big one.

As specified in the commit: 

> This commit integrated smooth_and crop.m and setup_medium.m across setup variants to harmonise how tissues are labeled. All previously hardcoded tissue labels are now referring to the config. The medium mask output of pseudo-CT generation has been reindexed according to the default layered setup and the conversion to tissue mask labels is performed in smooth_and_crop.m similar to the original layered setup. Minor documentation additions. Function getidx.m has been added to rapidly grab tissue labels from the parameters structure.

I forgot a few things in there:
- Now all figures up to simulation onset should be consistently saved via `saveas` with individual figure handles. This should avoid any saved figures with grey background.
- In addition to pseudoCT, smooth_and crop.m now also handles the scenario of a skull-only setup, removing the need for an independent function.

I am currently running both `layered` and `layered+pCT` variants. Up to simulation onset, the output looks correct.

**Comment by KTZ228** [comment]
Running my pipeline with this new version mostly seems to work.
However, it completes the heating simulations and writes the output to the csv and line graph before stopping prematurely.
It prints the following info about two figures in the output log:
Scherm­afbeelding 2024-08-02 om 16 26 07

And then gives the following error:
Scherm­afbeelding 2024-08-02 om 16 27 11.

Config used (extension changed to txt because GitHub doesn't support yaml):
[config_kenneth_phd_1_amygdala_exploratory_PCD15287_01002_left_65mm kopie.txt](https://github.com/user-attachments/files/16471738/config_kenneth_phd_1_amygdala_exploratory_PCD15287_01002_left_65mm.kopie.txt)

**Comment by jkosciessa** [comment]
@KTZ228 Thanks for checking. If I understand you correctly, the main problem is the specification of ```parameters.desired_intensity``` during the plotting of heating. This is indeed not necessary and I now removed it.

[55036b1](https://github.com/Donders-Institute/PRESTUS/pull/34/commits/55036b1d546a1ed9c150cb9cdf7c453b7a61ae30) now also allows to specify different starting temperatures for different tissues (I think a reasonable assumption). If this is not desired, adjusting the config to 37C for all tissues should restore the prior default.

**Comment by KTZ228** [comment]
After the bugfix regarding `parameters.thermal.temp_0.brain` it works for my pipeline.
However, the heating results are still unreasonably high. Hitting up to 10 degrees for an offline stimulation protocol using an `alpha_0_true: 13.3` & `alpha_power_true: 1`.

**Comment by KTZ228** [comment]
Also found a small bug that already existed in the pipeline at line 111 of the single_subject_pipeline:
replace:
```
        filename_t1 = fullfile(parameters.data_path, sprintf(parameters.t1_path_template, subject_id));
        if ~isfile(filename_t1)
            error('File does not exist: \r\n%s', filename_t1);
        end
```
with:
```
        filename_t1 = dir(fullfile(parameters.data_path, sprintf(parameters.t1_path_template, subject_id)));
        if isempty(filename_t1)
            error('File does not exist: \r\n%s', filename_t1);
        end
        filename_t1 = fullfile(filename_t1(1).folder, filename_t1(1).name);
```

**Comment by jkosciessa** [comment]
> After the bugfix regarding `parameters.thermal.temp_0.brain` it works for my pipeline. However, the heating results are still unreasonably high. Hitting up to 10 degrees for an offline stimulation protocol using an `alpha_0_true: 13.3` & `alpha_power_true: 1`.

I wonder whether this is indeed unreasonable. But you are now stuck at the same place as me. One thing to consider is that this global skull attenuation may be reasonable to estimate how much intensity is reduced, but it will likely overestimate heating. Skull attenuation is dominated by shear waves (scattering etc.), whereas [heating is dominated by compressional waves](https://ieeexplore.ieee.org/document/7329586). [2.7 dB may be a better estimate for compressional wave attenuation at 1 MHz](https://pubmed.ncbi.nlm.nih.gov/22225300/). As such, the current spec appears more suited to pressure estimation, while overestimating heating.

**Comment by KTZ228** [comment]
`run_segmentation` still only contains qsub code, so the segmentation can't yet be run on the new slurm cluster.

**Review by KTZ228 — APPROVED** [review]
After the small issues I was having over the summer have been fixed, the pipeline has been stable for the last couple of weeks.

**Comment by jkosciessa** [comment]
@MaCuinea Something may have gone wrong with your original merge. I have reverted your original merge (but not your subsequent update) on the development branch and accepted the original pull request. This way we do not lose the original commit messages and history.

**Pull request merged**
